security:
  ignored: /**

spring:
  data:
    mongodb:
      uri: mongodb+srv://potluck:potluck@cluster0-smvcu.mongodb.net/
      database: dcl
server:
  servlet:
    context-path: /

app:
  client:
    url: allibilli.com/potluck